import { dateAsString } from '../__global__.js';
import * as Types from '../index.js';

export type POST_api_lynt = {
    "id": Types.global.numberAsString,
    "user_id": Types.global.numberAsString,
    "content": string,
    "views": number,
    "shares": number,
    "has_link": boolean,
    "has_image": boolean,
    "created_at": Types.global.dateAsString,
    "reposted": boolean,
    "parent": null
}

export type Lynt = {
    "id": Types.global.numberAsString,
    "content": string,
    "userId": Types.global.numberAsString,
    "createdAt": Types.global.dateAsString,
    "views": Types.global.numberAsString,
    "reposted": boolean,
    "parentId": Types.global.numberAsString | null,
    "has_image": boolean,
    "likeCount": Types.global.numberAsString,
    "likedByFollowed": boolean,
    "repostCount": Types.global.numberAsString,
    "commentCount": Types.global.numberAsString,
    "likedByUser": boolean,
    "repostedByUser": boolean,
    "handle": string,
    "bio": string,
    "userCreatedAt": Types.global.dateAsString,
    "username": string,
    "iq": number,
    "verified": boolean,
    "parentContent": string | null,
    "parentHasImage": boolean | null,
    "parentUserHandle": string | null,
    "parentUserCreatedAt": Types.global.dateAsString | null,
    "parentUserBio": string | null,
    "parentUserUsername": string | null,
    "parentUserVerified": boolean | null,
    "parentUserIq": number | null,
    "parentUserId": Types.global.numberAsString | null,
    "parentCreatedAt": Types.global.dateAsString | null,
}

export type Lynt_fixed = {
    "id": Types.global.numberAsString,
    "content": string,
    "userId": Types.global.numberAsString,
    "createdAt": Date,
    "views": number,
    "reposted": boolean,
    "parentId": Types.global.numberAsString | null,
    "has_image": boolean,
    "likeCount": number,
    "likedByFollowed": boolean,
    "repostCount": number,
    "commentCount": number,
    "likedByUser": boolean,
    "repostedByUser": boolean,
    "handle": string,
    "bio": string,
    "userCreatedAt": Date,
    "username": string,
    "iq": number,
    "verified": boolean,
    "parentContent": string | null,
    "parentHasImage": boolean | null,
    "parentUserHandle": string | null,
    "parentUserCreatedAt": Date | null,
    "parentUserBio": string | null,
    "parentUserUsername": string | null,
    "parentUserVerified": boolean | null,
    "parentUserIq": number | null,
    "parentUserId": Types.global.numberAsString | null,
    "parentCreatedAt": Date | null,
}

export type GET_api_me = {
    "id": Types.global.numberAsString,
    "username": string,
    "handle": string,
    "created_at": dateAsString
    "iq": number,
}